variable "apiname" {}
variable "stage_name" {}
variable "resource_name" {}
variable "resource_name1" {}
variable "region" {}
variable "account_no" {}
variable "lambda_function_name" {}
variable "lambda_function_name1" {}
variable "lambda_function_name2" {}
variable "lambda_function_name3" {}
variable "lambda_function_name4" {}
variable "lambda_function_name5" {}
variable "lambda_function_name6" {}
variable "runtime" {}
variable "method" {}
variable "method1" {}
variable "method2" {}
variable "method3" {}
variable "user_pool_arn" {}
variable "event_bus_arn_devaccount_b" {}